[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[project]
name = "mycelial"
description = "mycelial python bindings"
requires-python = ">=3.9"
license = {text = "Apache-2.0"}
dependencies = [
    "websockets==10.3"
]

[tool.maturin]
python-source = "python"
